apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: deanrtaylor/financeapi
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-finance-uri
                  key: MONGO_URI
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: NODEMAIL_PASS
              valueFrom:
                secretKeyRef:
                  name: nodemail-pass
                  key: NODEMAIL_PASS
            - name: RDS_HOST
              valueFrom:
                secretKeyRef:
                  name: rds-host
                  key: RDS_HOST
            - name: RDS_USER
              valueFrom:
                secretKeyRef:
                  name: rds-user
                  key: RDS_USER
            - name: RDS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rds-password
                  key: RDS_PASSWORD
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: google-client-id
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: google-client-secret
                  key: GOOGLE_CLIENT_SECRET
            - name: FACEBOOK_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: facebook-client-id
                  key: FACEBOOK_CLIENT_ID
            - name: FACEBOOK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: facebook-client-secret
                  key: FACEBOOK_CLIENT_SECRET
            - name: GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: github-client-id
                  key: GITHUB_CLIENT_ID
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: github-client-secret
                  key: GITHUB_CLIENT_SECRET
            - name: STOCKS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: stocks-api-key
                  key: STOCKS_API_KEY
            - name: API_URL
              value: 'http://www.myfinapi.dev/'
            - name: CLIENT_URL
              valueFrom:
                secretKeyRef:
                  name: client-url
                  key: CLIENT_URL
---
apiVersion: v1
kind: Service
metadata:
  name: api-srv
spec:
  selector:
    app: api
  ports:
    - name: api
      protocol: TCP
      port: 3000
      targetPort: 3000
