apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: deanrtaylor/financeauth
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-finance-uri
                  key: MONGO_URI
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: NODEMAIL_PASS
              valueFrom:
                secretKeyRef:
                  name: nodemail-pass
                  key: NODEMAIL_PASS
            - name: RDS_HOST
              valueFrom:
                secretKeyRef:
                  name: rds-host
                  key: RDS_HOST
            - name: RDS_USER
              valueFrom:
                secretKeyRef:
                  name: rds-user
                  key: RDS_USER
            - name: RDS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rds-password
                  key: RDS_PASSWORD
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: google-client-id
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: google-client-secret
                  key: GOOGLE_CLIENT_SECRET
            - name: FACEBOOK_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: facebook-client-id
                  key: FACEBOOK_CLIENT_ID
            - name: FACEBOOK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: facebook-client-secret
                  key: FACEBOOK_CLIENT_SECRET
            - name: GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: github-client-id
                  key: GITHUB_CLIENT_ID
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: github-client-secret
                  key: GITHUB_CLIENT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
